include ~/.cache/wal/colors-kitty.conf

window_padding_width 10
background_opacity 0.8

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Bold
bold_font        family='JetBrainsMono Nerd Font' style=Bold
italic_font      auto
bold_italic_font auto
font_size 12
# END_KITTY_FONTS

# Enable mouse reporting (needed for some applications like vim, etc.)
mouse_reporting yes

# Automatically copy to clipboard when selecting text
copy_on_select clipboard

# Map middle-click to paste from the primary selection
mouse_map middle release ungrabbed paste_from_selection

# Map left-click to start selecting text
mouse_map left press ungrabbed mouse_selection normal
